---
version: "2.0.45"
name: Simple Scheduler
description: Simple timer on weekly base
slug: simplescheduler
url: https://github.com/arthurdent75/SimpleScheduler
codenotary: notary@home-assistant.io
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
homeassistant_api: true
ingress: true
panel_title: Scheduler
panel_icon: mdi:calendar-clock
map:
  - share:rw
