---
version: "3.2.1"
name: Simple Scheduler
description: Simple timer on weekly base
slug: simplescheduler
url: https://github.com/arthurdent75/SimpleScheduler
arch:
  - aarch64
  - amd64
  - armv7
image: ghcr.io/arthurdent75/simplescheduler
init: false
homeassistant_api: true
ingress: true
panel_admin: false
panel_title: Scheduler
panel_icon: mdi:calendar-clock
map:
  - share:rw
